// Data catalogs extracted from app.js to keep the entry script focused on behavior/state.

const CATS = [
  {id:'all',label:'All'},{id:'drums',label:'Drums'},{id:'strings',label:'Strings'},
  {id:'keys',label:'Keys'},{id:'vocals',label:'Vocals'},{id:'brass',label:'Brass'},
  {id:'infra',label:'Infra'},
];

const ICON_ASSET_BY_TYPE = {
  drumkit:'images/drums.png',
  acguitar:'images/acustic_guitar.png',
  elguitar:'images/eletric_guitar.png',
  bass:'images/bass.png',
  violin:'images/violin.png',
  cello:'images/cello.png',
  viola:'images/viola.png',
  harp:'images/harp.png',
  piano:'images/grand_piano.png',
  keys:'images/keys.png',
  vox:'images/mic_vocal.png',
  wirelessmic:'images/wireless_mic.png',
  wirelessreceiver:'images/wireless_receiver.png',
  bgvox:'images/mic_backvocal.png',
  talkback:'images/mic_talkback.png',
  trumpet:'images/trumpet.png',
  trombone:'images/trombone.png',
  sax:'images/sax.png',
  flute:'images/flute.png',
  monitor:'images/monitor.png',
  p16:'images/p16.png',
  p16d:'images/P16-D.png',
  pm1:'images/pm1.png',
  ha8000:'images/ha8000.png',
  ha400:'images/ha400.png',
  mainspk:'images/main_speaker.png',
  subwoofer:'images/subwoofer.png',
  scarlet2i2:'images/scarlet2i2.png',
  xr18:'images/xr18.png',
  m32:'images/m32.png',
  m32r:'images/m32r.png',
  x32:'images/x32_full.png',
  x32compact:'images/x32_compact.png',
  x32rack:'images/x32_rack.png',
  wing:'images/wing_full.png',
  wingcompact:'images/wing_compact.png',
  wingrack:'images/wing_rack.png',
  snake8:'images/snake8.png',
  snake16:'images/snake16.png',
  snake24:'images/snake24.png',
  snake32:'images/snake32.png',
  s32:'images/s32.png',
  s16:'images/s16.png',
  pulpit:'images/pulpit.png',
  di:'images/di.png',
  amp:'images/speaker_amp.png',
  poweramp:'images/power_amp.png',
  router:'images/router.png',
  pedals:'images/pedal.png',
  pedal:'images/pedal.png',
  laptop:'images/laptop.png',
  midipad:'images/midi_pad.png',
  micstand:'images/mic_stand.png',
  micstandmulti:'images/mic_stand_multiple.png',
  chair:'images/wood_chair.png',
  plasticchair:'images/plastic_chair.png',
  woodtable:'images/wood_table.png',
  pianosit:'images/piano_seat.png',
  sheetstand:'images/sheet_stand.png',
};

const INSTRUMENTS = [
  {type:'drumkit',   cat:'drums',   icon:'🥁', name:'Drum Kit',      wide:true,  size:92, connSide:'bottom' },
  {type:'acguitar',  cat:'strings', icon:'🎸', name:'AC-G', wide:false, size:56, connSide:'bottom'},
  {type:'elguitar',  cat:'strings', icon:'🎸', name:'EL-G', wide:false, size:56, connSide:'bottom'},
  {type:'bass',      cat:'strings', icon:'🎸', name:'EL-B',            wide:false, size:58, connSide:'bottom'},
  {type:'violin',    cat:'strings', icon:'🎻', name:'Violin',          wide:false, size:48, connSide:'bottom'},
  {type:'cello',     cat:'strings', icon:'🎻', name:'Cello',           wide:false, size:62, footprintAspect:0.52, connSide:'bottom'},
  {type:'viola',     cat:'strings', icon:'🎻', name:'Viola',           wide:false, size:50, connSide:'bottom'},
  {type:'harp',      cat:'strings', icon:'🎻', name:'Harp',            wide:false, size:66, footprintAspect:0.56, connSide:'bottom'},
  {type:'piano',     cat:'keys',    icon:'🎹', name:'Grand Piano',   wide:true,  size:110, footprintAspect:0.62, stereo:true, connSide:'bottom' },
  {type:'keys',      cat:'keys',    icon:'🎹', name:'Keys',          wide:false, size:68, footprintAspect:1.9, stereo:true, connSide:'bottom' },
  {type:'vox',       cat:'vocals',  icon:'🎤', name:'Vocal',         wide:false, size:46, connSide:'bottom'},
  {type:'wirelessmic',cat:'vocals', icon:'🎤', name:'Wireless Mic',   wide:false, size:46, connSide:'bottom'},
  {type:'bgvox',     cat:'vocals',  icon:'🎙', name:'BG Vox',        wide:false, size:46, connSide:'bottom'},
  {type:'talkback',  cat:'vocals',  icon:'📢', name:'Talkback Mic',  wide:false, size:46, connSide:'bottom'},
  {type:'m32',       cat:'mixers',  icon:'🎚', name:'M32',           wide:true,  size:114, connSide:'bottom', isMixer:true, mixerInputs:38, mixerInputXlrOnly:32, mixerInputCombo:0, mixerInputJackOnly:6, mixerAux:16, mixerMain:0, mixerJackOut:6, mixerP16:1, mixerAes50:2},
  {type:'m32r',      cat:'mixers',  icon:'🎚', name:'M32R',          wide:true,  size:108, connSide:'bottom', isMixer:true, mixerInputs:22, mixerInputXlrOnly:16, mixerInputCombo:0, mixerInputJackOnly:6, mixerAux:8, mixerMain:0, mixerJackOut:6, mixerP16:1, mixerAes50:2},
  {type:'pulpit',    cat:'vocals',  icon:'🎙', name:'Pulpit',        wide:false, size:52, footprintAspect:0.9, connSide:'bottom'},
  {type:'trumpet',   cat:'brass',   icon:'🎺', name:'Trumpet',     wide:false, size:50, connSide:'bottom'},
  {type:'trombone',  cat:'brass',   icon:'🎺', name:'Trombone',    wide:false, size:56, connSide:'bottom'},
  {type:'sax',       cat:'brass',   icon:'🎷', name:'Sax',         wide:false, size:52, connSide:'bottom'},
  {type:'flute',     cat:'brass',   icon:'🎼', name:'Flute',       wide:false, size:50, connSide:'bottom'},
  {type:'monitor',   cat:'monitoring', icon:'🔊', name:'Monitor',     wide:false, size:54, connSide:'top', requiresOutput:true},
  {type:'iem',       cat:'monitoring', icon:'🎧', name:'In-Ears',     wide:false, size:44, connSide:'top', requiresOutput:true},
  {type:'headphones',cat:'monitoring', icon:'🎧', name:'Headphones',  wide:false, size:44, connSide:'top', requiresOutput:true},
  {type:'p16',       cat:'monitoring', icon:'🔷', name:'P16',         wide:false, size:30, connSide:'top', requiresOutput:true},
  {type:'p16d',      cat:'monitoring', icon:'🔷', image:'images/P16-D.png', name:'P16-D', wide:true, size:82, footprintAspect:2.05, connSide:'bottom'},
  {type:'pm1',       cat:'monitoring', icon:'🔶', name:'PM1',         wide:false, size:30, connSide:'top', requiresOutput:true},
  {type:'ha8000',    cat:'monitoring', icon:'🎚', name:'HA8000',      wide:true,  size:84, connSide:'bottom', haUseMainInputs:false},
  {type:'ha400',     cat:'monitoring', icon:'🎧', name:'HA400',       wide:false, size:30, connSide:'bottom'},
  {type:'mainspk',   cat:'monitoring', icon:'🔊', name:'Main Speaker', wide:false, size:58, connSide:'top', requiresOutput:true},
  {type:'subwoofer', cat:'monitoring', icon:'🟫', name:'Subwoofer',    wide:false, size:62, connSide:'top', requiresOutput:true},
  {type:'xr18',        cat:'mixers',  icon:'🎛', name:'XR18 Mixer',      wide:true,  size:108, connSide:'bottom', isMixer:true, mixerInputs:18, mixerInputXlrOnly:0, mixerInputCombo:16, mixerInputJackOnly:2, mixerAux:6,  mixerMain:2, mixerJackOut:0, mixerP16:1, mixerAes50:0},
  {type:'x32',         cat:'mixers',  icon:'🎚', name:'X32 Full',        wide:true,  size:114, connSide:'bottom', isMixer:true, mixerInputs:38, mixerInputXlrOnly:32, mixerInputCombo:0,  mixerInputJackOnly:6, mixerAux:16, mixerMain:0, mixerJackOut:6, mixerP16:1, mixerAes50:2},
  {type:'x32compact',  cat:'mixers',  icon:'🎚', name:'X32 Compact',     wide:true,  size:108, connSide:'bottom', isMixer:true, mixerInputs:22, mixerInputXlrOnly:16, mixerInputCombo:0,  mixerInputJackOnly:6, mixerAux:8,  mixerMain:0, mixerJackOut:6, mixerP16:1, mixerAes50:2},
  {type:'x32rack',     cat:'mixers',  icon:'🎚', name:'X32 Rack',        wide:true,  size:104, connSide:'bottom', isMixer:true, mixerInputs:22, mixerInputXlrOnly:16, mixerInputCombo:0,  mixerInputJackOnly:6, mixerAux:8,  mixerMain:0, mixerJackOut:6, mixerP16:1, mixerAes50:2},
  {type:'wing',        cat:'mixers',  icon:'🪽', name:'WING Full',       wide:true,  size:116, connSide:'bottom', isMixer:true, mixerInputs:16, mixerInputXlrOnly:0,  mixerInputCombo:8,  mixerInputJackOnly:8, mixerAux:8,  mixerMain:0, mixerJackOut:8, mixerP16:0, mixerAes50:3},
  {type:'wingcompact', cat:'mixers',  icon:'🪽', name:'WING Compact',    wide:true,  size:110, connSide:'bottom', isMixer:true, mixerInputs:24, mixerInputXlrOnly:0,  mixerInputCombo:24, mixerInputJackOnly:0, mixerAux:8,  mixerMain:0, mixerJackOut:0, mixerP16:0, mixerAes50:3},
  {type:'wingrack',    cat:'mixers',  icon:'🪽', name:'WING Rack',       wide:true,  size:106, connSide:'bottom', isMixer:true, mixerInputs:24, mixerInputXlrOnly:0,  mixerInputCombo:24, mixerInputJackOnly:0, mixerAux:8,  mixerMain:0, mixerJackOut:0, mixerP16:0, mixerAes50:3},
  {type:'s32',         cat:'stageboxes', icon:'📦', name:'S32 Stagebox', wide:true,  size:102, connSide:'bottom', isMixer:true, mixerInputs:32, mixerInputXlrOnly:32, mixerInputCombo:0, mixerInputJackOnly:0, mixerAux:16, mixerMain:0, mixerJackOut:0, mixerP16:1, mixerAes50:2},
  {type:'s16',         cat:'stageboxes', icon:'📦', name:'S16 Stagebox', wide:true,  size:96,  connSide:'bottom', isMixer:true, mixerInputs:16, mixerInputXlrOnly:16, mixerInputCombo:0, mixerInputJackOnly:0, mixerAux:8,  mixerMain:0, mixerJackOut:0, mixerP16:1, mixerAes50:2},
  {type:'di',        cat:'accessories',   icon:'📦', name:'DI',      wide:false, size:22, connSide:'bottom'},
  {type:'amp',       cat:'accessories', icon:'🔌', image:'images/speaker_amp.png', name:'Speaker Amp', wide:false, size:60, connSide:'bottom', stereo:false, inputStereo:false, outputStereo:false},
  {type:'poweramp',  cat:'monitoring', icon:'🔌', image:'images/power_amp.png', name:'Power Amp', wide:true, size:84, connSide:'bottom', ampOutputs:4},
  {type:'pedals',    cat:'accessories',   icon:'🎛', name:'Pedals',      wide:false, size:22, connSide:'bottom'},
  {type:'scarlet2i2',cat:'accessories', icon:'🎛', name:'Scarlett 2i2', wide:true,  size:68, connSide:'bottom'},
  {type:'router',    cat:'accessories', icon:'📶', image:'images/router.png', name:'Router', wide:true, size:84, footprintAspect:2.2, connSide:'bottom', outletPorts:4},
  {type:'outlet',    cat:'accessories', icon:'◉', name:'Outlet',   wide:false, size:30, connSide:'bottom', connectionBoxKind:'outlet', outletConnectorType:'ethernet', outletPorts:2, outletPlacement:'wall'},
  {type:'micstand',  cat:'stands', icon:'🎙', name:'Mic Stand',         wide:false, size:54, footprintAspect:0.44, noConnect:true},
  {type:'micstandmulti',cat:'stands', icon:'🎙', name:'Mic Stand (Multi-Rest)', wide:false, size:58, footprintAspect:0.48, noConnect:true},
  {type:'chair',     cat:'stands', icon:'🪑', name:'Wood Chair',        wide:false, size:46, footprintAspect:1, noConnect:true},
  {type:'plasticchair', cat:'stands', icon:'🪑', name:'Plastic Chair',  wide:false, size:35, footprintAspect:1, noConnect:true},
  {type:'woodtable', cat:'stands', icon:'🪑', name:'Wood Table',        wide:false, size:135, footprintAspect:1.85, noConnect:true},
  {type:'pianosit',  cat:'stands', icon:'🪑', name:'Piano Sit',         wide:false, size:60, footprintAspect:1.71, noConnect:true},
  {type:'sheetstand',cat:'stands', icon:'🎼', name:'Sheet Stand',       wide:false, size:54, footprintAspect:0.58, noConnect:true},
  {type:'laptop',    cat:'infra',   icon:'💻', name:'Laptop',      wide:false, size:22, connSide:'right'},
  {type:'midipad',   cat:'infra',   icon:'🟦', name:'MIDI Pad',    wide:false, size:48, connSide:'right'},
];

const SNAKES = [
  {type:'snake8',  name:'8-ch Snake',  channels:8,  outputs:0 },
  {type:'snake16', name:'16-ch Snake', channels:16, outputs:4 },
  {type:'snake24', name:'24-ch Snake', channels:24, outputs:8 },
  {type:'snake32', name:'32-ch Snake', channels:32, outputs:8 },
];

const MIC_OPTIONS_BASE = [
  'Shure SM58',
  'Shure SM57',
  'Shure Centraverse CVG18',
  'the t.bone Ovid',
  'the t.bone Lucan',
  'Rode M5',
  'AKG C1000S',
  'AKG HT45 (wireless)',
  'AKG P4 (Drums)',
  'AKG P2 (Kick)',
  'AKG P17 (OH)',
];

const CUSTOM_MIC_STORAGE_KEY = 'stage-designer-custom-mics-v1';